import turtle

screen = turtle.Screen()
screen.bgcolor("black")
screen.setup(width=0.90, height=0.90, startx=0, starty=0)
screen.title("Moni <3")
pen = turtle.Turtle()
pen.speed(2)
pen.width(5)
pen.pencolor("pink")

def I():
    pen.pencolor("black")
    pen.goto(-250, 0)
    pen.pencolor("pink")
    pen.right(90)
    pen.forward(120)
    pen.right(90)
    pen.forward(60)
    pen.right(180)
    pen.forward(120)
    pen.right(180)
    pen.forward(60)
    pen.right(90)
    pen.forward(220)
    pen.left(90)
    pen.forward(60)
    pen.left(180)
    pen.forward(120)

def heart():
    pen.pencolor("black")
    pen.goto(-80, -22)
    pen.pencolor("red")
    pen.left(45)
    pen.forward(100)
    pen.left(180)
    pen.forward(100)
    pen.left(90)
    pen.forward(100)
    pen.speed(2*10)
    pen.pencolor("black")
    pen.goto(50, 0)
    for angle in range(250):
        if angle > 40:
            pen.pencolor("red")
        pen.forward(1)
        pen.left(1)
    pen.pencolor("black")
    pen.goto(50, 0)
    pen.left(110)
    for angle in range(40):
        pen.forward(1)
        pen.left(1)
    pen.pencolor("red")
    for angle in range(190):
        pen.forward(1)
        pen.right(1)

def U():
    pen.pencolor("black")
    pen.left(90)
    pen.forward(75)
    pen.left(90)
    pen.forward(100)
    pen.goto(260, 100)
    pen.right(75)
    pen.pencolor("pink")
    pen.speed(2)
    pen.forward(155)
    pen.speed(50)
    for angle in range(180):
        pen.forward(1.25)
        pen.left(1)
    pen.speed(2)
    pen.forward(155)

I()
heart()
U()
turtle.done()
